### PR TITLE
Force fetch config when cache empty

### PR DESCRIPTION
**Pull request by davidmoss**
Always ensure that the cache is fetched, ignoring the etag if the cache is empty.

### CODE REVIEW

**Comment by sigewuzhere** [comment]
@davidmoss Thank you for the PR! We'll review it as we can.

**Comment by kp-cat** [comment]
@davidmoss Thanks for the PR! It seems reasonable.
Could you please use our coding style:
- Single quotes strings
- If/while without brackets

**Comment by davidmoss** [comment]
@kp-cat done!

**Comment by kp-cat** [comment]
@davidmoss Thanks. I would add some extra checks to the tests.
I've created a patch based on your `kantanhq:force-fetch-empty-cache branch`
(to do that with github suggestions it would be a pain)
Can please you apply this patch on your PR (if you agree with it).

[patch.diff.zip](https://github.com/configcat/python-sdk/files/4927932/patch.diff.zip)

**Comment by davidmoss** [comment]
@kp-cat thanks for the extra checks, all makes sense to me, so have added 👍

**Comment by kp-cat** [comment]
I merged back, thanks again for the issue and the PR. We will release it today.

**Pull request merged**
